package GYM;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nurhan
 */
public class AssginMembertoTrainer extends javax.swing.JFrame {
    int IDOfMember;
    int IDOfTrainer;
    String SelectedValue="Choose";
    String Allmembers="";
    String CodeMember="";
    String CodeTrainer="";
    
    /**
     * Creates new form AllmembersDesign
     */
    public AssginMembertoTrainer() {
        initComponents();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDeletePanel = new javax.swing.JPanel();
        Viewbutton = new javax.swing.JButton();
        chooselabel = new javax.swing.JLabel();
        Choosebox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayList = new javax.swing.JTextArea();
        CloseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TrainerID = new javax.swing.JTextField();
        AssginBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MemberID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ClassesHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 250));
        setUndecorated(true);

        UpdateDeletePanel.setBackground(new java.awt.Color(204, 204, 204));
        UpdateDeletePanel.setToolTipText("");

        Viewbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Viewbutton.setForeground(new java.awt.Color(51, 51, 51));
        Viewbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        Viewbutton.setText("View Members");
        Viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbuttonActionPerformed(evt);
            }
        });

        chooselabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        chooselabel.setForeground(new java.awt.Color(51, 51, 51));
        chooselabel.setText(" Choose member list or a specific membership");

        Choosebox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Choosebox.setForeground(new java.awt.Color(102, 102, 102));
        Choosebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "All members info", "Daily access", "Monthly Membership", "Six Month Membership", "One year Membership", " " }));
        Choosebox.setToolTipText("");
        Choosebox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Choosebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseboxActionPerformed(evt);
            }
        });

        DisplayList.setEditable(false);
        DisplayList.setColumns(20);
        DisplayList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DisplayList.setForeground(new java.awt.Color(51, 51, 51));
        DisplayList.setRows(5);
        DisplayList.setText(" ");
        DisplayList.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(DisplayList);

        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Enter Private Trainer ID : ");

        TrainerID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TrainerID.setSelectionColor(new java.awt.Color(51, 51, 51));

        AssginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AssginBtn.setForeground(new java.awt.Color(51, 51, 51));
        AssginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        AssginBtn.setText("Add");
        AssginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssginBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Enter Member ID:  ");

        MemberID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MemberID.setSelectionColor(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Assgin Private Trainer");

        ClassesHeader.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        ClassesHeader.setForeground(new java.awt.Color(51, 51, 51));
        ClassesHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list of members.png"))); // NOI18N
        ClassesHeader.setText("Members & Memberships");

        javax.swing.GroupLayout UpdateDeletePanelLayout = new javax.swing.GroupLayout(UpdateDeletePanel);
        UpdateDeletePanel.setLayout(UpdateDeletePanelLayout);
        UpdateDeletePanelLayout.setHorizontalGroup(
            UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClassesHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDeletePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Choosebox, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TrainerID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118)
                                .addComponent(AssginBtn))
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(76, 76, 76)
                                .addComponent(Viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(chooselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateDeletePanelLayout.setVerticalGroup(
            UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CloseBtn)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ClassesHeader)))
                .addGap(28, 28, 28)
                .addComponent(chooselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Choosebox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDeletePanelLayout.createSequentialGroup()
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TrainerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(AssginBtn)
                        .addGap(3, 3, 3)))
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UpdateDeletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UpdateDeletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseboxActionPerformed
     SelectedValue = Choosebox.getSelectedItem().toString(); 
     DisplayList.setText("");
    
    }//GEN-LAST:event_ChooseboxActionPerformed

    private void ViewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbuttonActionPerformed
       
     if(SelectedValue=="All members info")
     {   
        for (Member mem1 : GymMangement.members)
        { 
            Allmembers=Allmembers.concat("Name: "+mem1.Name +"   ID: "+ String.valueOf(mem1.code)+"   Membership: "+mem1.membership.Membershipname+"   Age: "+String.valueOf(mem1.Age)+"   Phone Number: "+mem1.phonenumber+"   SSN: "+String.valueOf(mem1.Ssn)+"  Gender: "+mem1.Gender+"  Assigned trainer: "+mem1.TrainerName+' '+mem1.TrainerID + "\n\n");
        }      
          DisplayList.setText(Allmembers);
          Allmembers="";
     }
     else
     {
        for (Member mem1 : GymMangement.members)
        {
            if(mem1.membership.Membershipname==SelectedValue)
            {
                Allmembers=Allmembers.concat("Name: "+mem1.Name +"   ID: "+ String.valueOf(mem1.code)+"   Membership: "+mem1.membership.Membershipname+"   Age: "+String.valueOf(mem1.Age)+"   Phone Number: "+mem1.phonenumber+"   SSN: "+String.valueOf(mem1.Ssn)+"  Gender: "+mem1.Gender+"  Assigned trainer: "+mem1.TrainerName+' '+mem1.TrainerID + "\n\n");
            }
        }      
          DisplayList.setText(Allmembers);
          Allmembers="";
     }

    }//GEN-LAST:event_ViewbuttonActionPerformed

    private void AssginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssginBtnActionPerformed

        boolean ExistsMember=false;
        boolean ExistsTrainer=false;
        try
        { 
            IDOfTrainer= Integer.parseInt(TrainerID.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please enter TrainerID you want to Assign"); ExistsTrainer=true;
        }
        try
        { 
            IDOfMember= Integer.parseInt(MemberID.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please enter MemberID you want to Assign"); ExistsMember=true;
        }
        
        for (Member mem : GymMangement.members)
        {

            if(mem.code==IDOfMember)
            {
                ExistsMember=true;
                for (Trainer tl : GymMangement.trainers)
                {
                    CodeTrainer=String.valueOf(tl.tranierID);
                            
                    if(tl.tranierID== IDOfTrainer)
                    {
                        ExistsTrainer=true; 
                        mem.TrainerName=tl.Name;
                        mem.TrainerID=tl.tranierID;      
                        TrainerID.setText("");
                    }
                }
                if(ExistsTrainer==false)
                {
                    JOptionPane.showMessageDialog(null,"There is no such Trainer.");
                }
                MemberID.setText("");
            }                            

        }
        if(ExistsMember==false)
        {
           JOptionPane.showMessageDialog(null,"There is no such Member.");
        }

    }//GEN-LAST:event_AssginBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssginMembertoTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssginMembertoTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssginMembertoTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssginMembertoTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssginMembertoTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssginBtn;
    private javax.swing.JComboBox<String> Choosebox;
    private javax.swing.JLabel ClassesHeader;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JTextArea DisplayList;
    private javax.swing.JTextField MemberID;
    private javax.swing.JTextField TrainerID;
    private javax.swing.JPanel UpdateDeletePanel;
    private javax.swing.JButton Viewbutton;
    private javax.swing.JLabel chooselabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
