package GYM;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bishoy
 */
public class ClassTrainer extends javax.swing.JFrame {

     String IDOfTrainer;
     String Classselectedvalue="Choose Class";
     String classInfo="";
     String[] data = new String[GymMangement.size];

    public ClassTrainer() {
        initComponents();
    }
    private void ViewClass()
    {
       for (Class c1 : GymMangement.classes)
       {
            if(c1.Classname==Classselectedvalue)
            {
                   
                classInfo=classInfo.concat("Name: "+c1.Classname + "\n" 
                +"Number of members in the class: "
                + String.valueOf(c1.Classmembers.size())
                + "\n" +"Assigned Trainer Name: "+c1.TrainerName
                + "\n" +"Assigned Trainer ID: "+String.valueOf(c1.trainerID));
            }           
       }      
       TrainersList.setText(classInfo);
       classInfo="";
    }

    private boolean Availability(Class cl,Trainer t1)
    {
        if(cl.Daytime.equals(t1.DayTime))
        {
            JOptionPane.showMessageDialog(null,"This Trainer is Already Assigned to a Class at the Same Time");
            return false;
        }
        else
        {
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDeletePanel = new javax.swing.JPanel();
        ClassesHeader1 = new javax.swing.JLabel();
        AssignButton = new javax.swing.JButton();
        Viewbutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ClassesBox = new javax.swing.JComboBox<>();
        Close_Button = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        AssignTrainers = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TrainersList = new javax.swing.JTextArea();
        lbl_ClassDescribe = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ClassDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 250));
        setUndecorated(true);

        UpdateDeletePanel.setBackground(new java.awt.Color(204, 204, 204));
        UpdateDeletePanel.setToolTipText("");

        ClassesHeader1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        ClassesHeader1.setForeground(new java.awt.Color(51, 51, 51));
        ClassesHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list of members.png"))); // NOI18N
        ClassesHeader1.setText("Assign Trainers Classes");

        AssignButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AssignButton.setForeground(new java.awt.Color(51, 51, 51));
        AssignButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        AssignButton.setText("Assign");
        AssignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignButtonActionPerformed(evt);
            }
        });

        Viewbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Viewbutton.setForeground(new java.awt.Color(51, 51, 51));
        Viewbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        Viewbutton.setText("View Class Info");
        Viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbuttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Classes");

        ClassesBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClassesBox.setForeground(new java.awt.Color(153, 153, 153));
        GymMangement.classnames.clear();
        for (Class cl : GymMangement.classes)
        {
            GymMangement.classnames.add(cl.Classname);
        }
        for(int i = 0; i < GymMangement.classnames.size(); i++)
        {
            data[i] = GymMangement.classnames.get(i);
        }
        ClassesBox.setModel(new javax.swing.DefaultComboBoxModel<>(data));
        ClassesBox.setToolTipText("");
        ClassesBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClassesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassesBoxActionPerformed(evt);
            }
        });

        Close_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Enter ID to Assign Trainers to Class:");

        AssignTrainers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AssignTrainers.setForeground(new java.awt.Color(255, 0, 0));
        AssignTrainers.setSelectionColor(new java.awt.Color(51, 51, 51));

        TrainersList.setEditable(false);
        TrainersList.setColumns(20);
        TrainersList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TrainersList.setForeground(new java.awt.Color(51, 51, 51));
        TrainersList.setRows(5);
        TrainersList.setText(" ");
        TrainersList.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane3.setViewportView(TrainersList);

        lbl_ClassDescribe.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_ClassDescribe.setForeground(new java.awt.Color(51, 51, 51));
        lbl_ClassDescribe.setText("Class description");

        ClassDescription.setEditable(false);
        ClassDescription.setColumns(20);
        ClassDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClassDescription.setForeground(new java.awt.Color(51, 51, 51));
        ClassDescription.setRows(5);
        ClassDescription.setText(" ");
        ClassDescription.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane4.setViewportView(ClassDescription);

        javax.swing.GroupLayout UpdateDeletePanelLayout = new javax.swing.GroupLayout(UpdateDeletePanel);
        UpdateDeletePanel.setLayout(UpdateDeletePanelLayout);
        UpdateDeletePanelLayout.setHorizontalGroup(
            UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(Viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(AssignButton))
                                    .addComponent(AssignTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ClassDescribe))
                                .addContainerGap(44, Short.MAX_VALUE))))
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClassesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(ClassesHeader1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Close_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        UpdateDeletePanelLayout.setVerticalGroup(
            UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(Close_Button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ClassesHeader1)))
                .addGap(45, 45, 45)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ClassDescribe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(ClassesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignButton))
                        .addGap(74, 74, 74))
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpdateDeletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpdateDeletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AssignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignButtonActionPerformed
        IDOfTrainer=AssignTrainers.getText();
        boolean Exists=false;
        try
        {
            if(Integer.parseInt(IDOfTrainer) > Trainer.NumberOfTrainers)
            {
                JOptionPane.showMessageDialog(null,"There is no such Trainer.");
            }
            else 
            {

                for (Trainer t1 : GymMangement.trainers)
                {
                    String codestring = String.valueOf(t1.tranierID);

                    if(codestring.equals (IDOfTrainer))
                    {
                        Exists=true;
                        for (Class cl : GymMangement.classes)
                        {
                            if(cl.Classname.equals(Classselectedvalue))
                            {
                                if(Availability(cl, t1)==true)
                                {
                                    t1.DayTime=cl.Daytime;
                                    cl.TrainerName=t1.Name;
                                    cl.trainerID=t1.tranierID;
                                }

                            }

                        }
                        AssignTrainers.setText("");
                    }
                    if(Exists==false)
                    {
                        JOptionPane.showMessageDialog(null,"There is no such Trainer.");
                    }
                }
                ViewClass();            
            }
            
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a Trainer ID to Assign.");
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_AssignButtonActionPerformed

    private void ViewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbuttonActionPerformed
        ViewClass();
    }//GEN-LAST:event_ViewbuttonActionPerformed

    private void ClassesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassesBoxActionPerformed
        Classselectedvalue = ClassesBox.getSelectedItem().toString();
        for (Class cl : GymMangement.classes)
        {
            if(cl.Classname == Classselectedvalue)
            {
                String g =cl.description;
                ClassDescription.setText(g);
            }
        }
        TrainersList.setText("");

    }//GEN-LAST:event_ClassesBoxActionPerformed

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Close_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignButton;
    private javax.swing.JTextField AssignTrainers;
    private javax.swing.JTextArea ClassDescription;
    private javax.swing.JComboBox<String> ClassesBox;
    private javax.swing.JLabel ClassesHeader1;
    private javax.swing.JButton Close_Button;
    private javax.swing.JTextArea TrainersList;
    private javax.swing.JPanel UpdateDeletePanel;
    private javax.swing.JButton Viewbutton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_ClassDescribe;
    // End of variables declaration//GEN-END:variables
}
