package GYM;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TOSHIBA
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Newmember = new javax.swing.JMenu();
        Updatebutton = new javax.swing.JMenu();
        memberships = new javax.swing.JMenu();
        Classes = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1018));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Welcome");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(755, 755, 755)
                .addComponent(jLabel1)
                .addContainerGap(875, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel1)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(20, 0, 90, 0));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 500));

        Newmember.setBackground(new java.awt.Color(0, 0, 0));
        Newmember.setForeground(new java.awt.Color(204, 204, 204));
        Newmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new member.png"))); // NOI18N
        Newmember.setText("New Member");
        Newmember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Newmember.setMargin(new java.awt.Insets(0, 0, 0, 100));
        Newmember.setOpaque(true);
        Newmember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewmemberMouseClicked(evt);
            }
        });
        jMenuBar1.add(Newmember);

        Updatebutton.setBackground(new java.awt.Color(0, 0, 0));
        Updatebutton.setForeground(new java.awt.Color(204, 204, 204));
        Updatebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update & delete member.png"))); // NOI18N
        Updatebutton.setText("Update & Delete Member ");
        Updatebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Updatebutton.setMargin(new java.awt.Insets(0, 0, 0, 75));
        Updatebutton.setOpaque(true);
        Updatebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatebuttonMouseClicked(evt);
            }
        });
        jMenuBar1.add(Updatebutton);

        memberships.setBackground(new java.awt.Color(0, 0, 0));
        memberships.setForeground(new java.awt.Color(204, 204, 204));
        memberships.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list of members.png"))); // NOI18N
        memberships.setText("Members & Memberships");
        memberships.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        memberships.setMargin(new java.awt.Insets(0, 0, 0, 75));
        memberships.setOpaque(true);
        memberships.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membershipsMouseClicked(evt);
            }
        });
        jMenuBar1.add(memberships);

        Classes.setBackground(new java.awt.Color(0, 0, 0));
        Classes.setForeground(new java.awt.Color(204, 204, 204));
        Classes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list of members.png"))); // NOI18N
        Classes.setText("Classes");
        Classes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Classes.setMargin(new java.awt.Insets(0, 0, 0, 95));
        Classes.setOpaque(true);
        Classes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassesMouseClicked(evt);
            }
        });
        jMenuBar1.add(Classes);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setForeground(new java.awt.Color(204, 204, 204));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setText("Log Out ");
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setMargin(new java.awt.Insets(0, 0, 0, 95));
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setMargin(new java.awt.Insets(0, 0, 0, 20));
        exit.setOpaque(true);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked

        int a=JOptionPane.showConfirmDialog(null, "Do you want to Exit the System" , "Select", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }

    }//GEN-LAST:event_exitMouseClicked

    private void ClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassesMouseClicked

        new ClassFrame().setVisible(true);

    }//GEN-LAST:event_ClassesMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you want to logout" , "Select", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            setVisible(false);
            new login().setVisible(true);
        }

    }//GEN-LAST:event_logoutMouseClicked

    private void membershipsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membershipsMouseClicked

        new AllmembersDesign().setVisible(true);

    }//GEN-LAST:event_membershipsMouseClicked

    private void UpdatebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebuttonMouseClicked

        new Update().setVisible(true);

    }//GEN-LAST:event_UpdatebuttonMouseClicked

    private void NewmemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewmemberMouseClicked

        new NewMember().setVisible(true);

    }//GEN-LAST:event_NewmemberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Classes;
    private javax.swing.JMenu Newmember;
    private javax.swing.JMenu Updatebutton;
    private javax.swing.JMenu exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu memberships;
    // End of variables declaration//GEN-END:variables
}
