package GYM;



import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TOSHIBA
 */
public class NewTrainer extends javax.swing.JFrame {

    /**
     * Creates new form NewTrainer
     */
    
    String codestring= String.valueOf(Trainer.NumberOfTrainers+1);//we use it in next trainer ID label
    StringBuilder Genderselectedvalue=new StringBuilder("Male");
    StringBuilder Shiftselectedvalue= new StringBuilder("9:00 AM - 3:00 PM");
   StringBuilder name=new StringBuilder("");
    StringBuilder phonenumber=new StringBuilder("");
    StringBuilder agestring=new StringBuilder("");
    StringBuilder ssnstring=new StringBuilder("");
    
    public NewTrainer() {
        initComponents();
    }
    private void ClearFileds(){
       Entername.setText(null);
       AgeText.setText(null);
       phonenumbertext.setText(null);
       SSNText.setText(null);
       SSNwarning.setVisible(false);
       Mobilewarning.setVisible(false);
       Namewarning.setVisible(false);
       Agewarning.setVisible(false);
       Genderbox.setSelectedItem("Male");
       ShiftTime.setSelectedItem("9:00 AM - 3:00 PM");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Entername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phonenumbertext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SSNText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Genderbox = new javax.swing.JComboBox<>();
        Savebutton = new javax.swing.JButton();
        Resetbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        AgeText = new javax.swing.JTextField();
        ShiftTime = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Namewarning = new javax.swing.JLabel();
        Agewarning = new javax.swing.JLabel();
        SSNwarning = new javax.swing.JLabel();
        Mobilewarning = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 250));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1043, 529));
        jPanel1.setMinimumSize(new java.awt.Dimension(1043, 529));
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new member.png"))); // NOI18N
        jLabel1.setText("New Trainer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Trainer ID");

        IDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(255, 51, 51));
        IDLabel.setText(" ");
        IDLabel.setText(codestring);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Name");

        Entername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Entername.setForeground(new java.awt.Color(51, 51, 51));
        Entername.setSelectionColor(new java.awt.Color(51, 51, 51));
        Entername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnternameActionPerformed(evt);
            }
        });
        Entername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnternameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Mobile Number");

        phonenumbertext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonenumbertext.setForeground(new java.awt.Color(51, 51, 51));
        phonenumbertext.setSelectionColor(new java.awt.Color(51, 51, 51));
        phonenumbertext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumbertextKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Age");

        SSNText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SSNText.setForeground(new java.awt.Color(51, 51, 51));
        SSNText.setSelectionColor(new java.awt.Color(51, 51, 51));
        SSNText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SSNTextKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Gender");

        Genderbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Genderbox.setForeground(new java.awt.Color(51, 51, 51));
        Genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderboxActionPerformed(evt);
            }
        });

        Savebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Savebutton.setForeground(new java.awt.Color(51, 51, 51));
        Savebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        Savebutton.setText("Save");
        Savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebuttonActionPerformed(evt);
            }
        });

        Resetbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resetbutton.setForeground(new java.awt.Color(51, 51, 51));
        Resetbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("SSN");

        AgeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgeText.setForeground(new java.awt.Color(51, 51, 51));
        AgeText.setSelectionColor(new java.awt.Color(51, 51, 51));
        AgeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeTextKeyPressed(evt);
            }
        });

        ShiftTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShiftTime.setForeground(new java.awt.Color(51, 51, 51));
        ShiftTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00 AM - 3:00 PM", "3:00 PM - 12:00 AM", "12:00 AM - 9:00 AM" }));
        ShiftTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiftTimeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Shift Time");

        Namewarning.setForeground(new java.awt.Color(255, 51, 51));
        Namewarning.setText("      ");
        Namewarning.setVisible(false);

        Agewarning.setForeground(new java.awt.Color(255, 51, 51));
        Agewarning.setText("         ");
        Agewarning.setVisible(false);

        SSNwarning.setForeground(new java.awt.Color(255, 51, 51));
        SSNwarning.setText("           ");
        SSNwarning.setVisible(false);

        Mobilewarning.setForeground(new java.awt.Color(255, 51, 51));
        Mobilewarning.setText("        ");
        Mobilewarning.setVisible(false);

        Exitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(phonenumbertext, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Entername, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(310, 310, 310)
                                                .addComponent(Savebutton))
                                            .addComponent(jLabel4)
                                            .addComponent(Namewarning, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mobilewarning, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Agewarning, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Resetbutton)
                                    .addComponent(SSNText, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(ShiftTime, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SSNwarning, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(160, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exitbutton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SSNwarning)
                    .addComponent(Namewarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonenumbertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShiftTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mobilewarning)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(IDLabel))
                .addGap(13, 13, 13)
                .addComponent(Agewarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savebutton)
                    .addComponent(Resetbutton))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderboxActionPerformed
        Genderselectedvalue.delete(0,7).append(Genderbox.getSelectedItem().toString());
    }//GEN-LAST:event_GenderboxActionPerformed

    private void SavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebuttonActionPerformed

    Trainer t1=new Trainer();
    try
    {
      t1.Add(Entername, AgeText, SSNText,phonenumbertext, ShiftTime, Genderbox, name,phonenumber,agestring,ssnstring, Shiftselectedvalue, Genderselectedvalue);
        if(TrainerValidation(name.toString(),ssnstring.toString(),phonenumber.toString(),agestring.toString())==true)
        { 
        t1 = new Trainer(name.toString(),ssnstring.toString(),phonenumber.toString(),Integer.parseInt(agestring.toString()),Genderselectedvalue.toString(),Shiftselectedvalue.toString(),"");        
        GymMangement.trainers.add(t1);
        codestring = String.valueOf(Trainer.NumberOfTrainers+1);
        IDLabel.setText(codestring);
        ClearFileds();
      
       }
    }
     catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,"Something's wrong please check the entered inputs.");
    
    }        
    }//GEN-LAST:event_SavebuttonActionPerformed

    private void ShiftTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftTimeActionPerformed

        Shiftselectedvalue.delete(0,20).append(ShiftTime.getSelectedItem().toString());
        
    }//GEN-LAST:event_ShiftTimeActionPerformed

    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbuttonActionPerformed

        ClearFileds();
        
    }//GEN-LAST:event_ResetbuttonActionPerformed

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
      
        setVisible(false);
        
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void EnternameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnternameKeyPressed
       
        Namewarning.setText(" ");
    }//GEN-LAST:event_EnternameKeyPressed

    private void EnternameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnternameActionPerformed
    }//GEN-LAST:event_EnternameActionPerformed

    private void phonenumbertextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumbertextKeyPressed
        Mobilewarning.setText(" ");
    }//GEN-LAST:event_phonenumbertextKeyPressed

    private void AgeTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTextKeyPressed
        Agewarning.setText(" ");
         
    }//GEN-LAST:event_AgeTextKeyPressed

    private void SSNTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SSNTextKeyPressed
        SSNwarning.setText(" ");
      
    }//GEN-LAST:event_SSNTextKeyPressed
    
    private Boolean TrainerValidation(String name, String ssn,String phonenumber ,String age)
    {
        
        if (name.length()==0)
        {  
            Namewarning.setVisible(true);
            Namewarning.setText("Please Enter The Name");
            Entername.requestFocusInWindow();
            return false;
        }

        
        if(phonenumber.length()==0) 
        { 
           Mobilewarning.setVisible(true);
           Mobilewarning.setText("Please Enter Mobile Number");
           phonenumbertext.requestFocusInWindow();
           return false;
        }

        if(age.length()==0) 
        { 
           Agewarning.setVisible(true);
           Agewarning.setText("Please Enter The Age");
           AgeText.requestFocusInWindow();
           return false;
        }
                        
        if(ssn.length()==0) 
        { 
           SSNwarning.setVisible(true);
           SSNwarning.setText("Please Enter The SSN");
           SSNText.requestFocusInWindow();
           return false;    
        }
        
        else
        {
            IDLabel.setText(codestring);
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JLabel Agewarning;
    private javax.swing.JTextField Entername;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JComboBox<String> Genderbox;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel Mobilewarning;
    private javax.swing.JLabel Namewarning;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JTextField SSNText;
    private javax.swing.JLabel SSNwarning;
    private javax.swing.JButton Savebutton;
    private javax.swing.JComboBox<String> ShiftTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phonenumbertext;
    // End of variables declaration//GEN-END:variables
}
