package GYM;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nurhan
 */
public class Update extends javax.swing.JFrame {

    int IDSearch;
    String Packageselectedvalue="Daily access";
    Member removedmember;
    String price=" ";

    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDeletePanel = new javax.swing.JPanel();
        Update_Delete_Header = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Entername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phonenumbertext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Agetext = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Close_Button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Membershipbox = new javax.swing.JComboBox<>();
        IDLabel = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        SearchIDButton = new javax.swing.JButton();
        Paymentlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 250));
        setUndecorated(true);

        UpdateDeletePanel.setBackground(new java.awt.Color(204, 204, 204));
        UpdateDeletePanel.setToolTipText("");

        Update_Delete_Header.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        Update_Delete_Header.setForeground(new java.awt.Color(51, 51, 51));
        Update_Delete_Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new member.png"))); // NOI18N
        Update_Delete_Header.setText("Update and Delete");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Name");

        Entername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Entername.setForeground(new java.awt.Color(51, 51, 51));
        Entername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnternameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Mobile Number");

        phonenumbertext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonenumbertext.setForeground(new java.awt.Color(51, 51, 51));
        phonenumbertext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumbertextKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Age");

        Agetext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Agetext.setForeground(new java.awt.Color(51, 51, 51));
        Agetext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgetextKeyPressed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(51, 51, 51));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        RemoveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RemoveButton.setForeground(new java.awt.Color(51, 51, 51));
        RemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Amount of Payment ");

        Close_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Membership");

        Membershipbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Membershipbox.setForeground(new java.awt.Color(51, 51, 51));
        Membershipbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily access", "Monthly Membership", "Six Month Membership", "One year Membership" }));
        Membershipbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembershipboxActionPerformed(evt);
            }
        });

        IDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(51, 51, 51));
        IDLabel.setText("ID");

        IDText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IDText.setForeground(new java.awt.Color(255, 0, 0));
        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });
        IDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IDTextKeyReleased(evt);
            }
        });

        lbl_name.setForeground(new java.awt.Color(255, 0, 0));
        lbl_name.setText(" ");

        lbl_ID.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ID.setText(" ");
        lbl_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_IDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_IDKeyReleased(evt);
            }
        });

        lbl_phone.setForeground(new java.awt.Color(255, 0, 0));
        lbl_phone.setText(" ");
        lbl_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_phoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_phoneKeyReleased(evt);
            }
        });

        lbl_age.setForeground(new java.awt.Color(255, 0, 0));
        lbl_age.setText(" ");
        lbl_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_ageKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_ageKeyReleased(evt);
            }
        });

        SearchIDButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchIDButton.setForeground(new java.awt.Color(51, 51, 51));
        SearchIDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        SearchIDButton.setText("Search ");
        SearchIDButton.setActionCommand("Search ID");
        SearchIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIDButtonActionPerformed(evt);
            }
        });

        Paymentlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Paymentlabel.setForeground(new java.awt.Color(255, 51, 51));
        Paymentlabel.setText(" ");

        javax.swing.GroupLayout UpdateDeletePanelLayout = new javax.swing.GroupLayout(UpdateDeletePanel);
        UpdateDeletePanel.setLayout(UpdateDeletePanelLayout);
        UpdateDeletePanelLayout.setHorizontalGroup(
            UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(Update_Delete_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Close_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(updateButton)
                                .addGap(72, 72, 72)
                                .addComponent(RemoveButton))
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addComponent(IDLabel)
                                .addGap(18, 18, 18)
                                .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(SearchIDButton))
                            .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(phonenumbertext, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(Entername, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Agetext, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_age, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(Membershipbox, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Paymentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        UpdateDeletePanelLayout.setVerticalGroup(
            UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateDeletePanelLayout.createSequentialGroup()
                        .addComponent(Close_Button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Update_Delete_Header)))
                .addGap(33, 33, 33)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchIDButton)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Membershipbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Paymentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(phonenumbertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbl_phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(Agetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_age)
                .addGap(56, 56, 56)
                .addGroup(UpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveButton)
                    .addComponent(updateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(UpdateDeletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(UpdateDeletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIDButtonActionPerformed
        boolean exists=false;
        try{IDSearch=Integer.parseInt(IDText.getText());}
        catch(Exception e){JOptionPane.showMessageDialog(null,"Please enter ID you want to search"); exists=true;}
        for (Member mem1 : GymMangement.members)
        {
            if(mem1.code==IDSearch)
            {
                exists=true;
                mem1.Dislayinfo(Entername, phonenumbertext, Agetext, Membershipbox, mem1.Name, mem1.phonenumber,mem1.Age,mem1.membership.Membershipname);
                price = String.valueOf(mem1.membership.price);
                Paymentlabel.setText(price);
            }
        }
        if(exists==false)
        {
            JOptionPane.showMessageDialog(null,"There is no such Member");
            ClearFields();
        }
    }//GEN-LAST:event_SearchIDButtonActionPerformed

    private void lbl_ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_ageKeyReleased

    }//GEN-LAST:event_lbl_ageKeyReleased

    private void lbl_ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_ageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ageKeyPressed

    private void lbl_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_phoneKeyReleased

    }//GEN-LAST:event_lbl_phoneKeyReleased

    private void lbl_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_phoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_phoneKeyPressed

    private void lbl_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_IDKeyReleased

    }//GEN-LAST:event_lbl_IDKeyReleased

    private void lbl_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_IDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_IDKeyPressed

    private void IDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyReleased

    }//GEN-LAST:event_IDTextKeyReleased

    private void IDTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyPressed
        
        lbl_ID.setText("");
        
    }//GEN-LAST:event_IDTextKeyPressed

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed

    }//GEN-LAST:event_IDTextActionPerformed

    private void MembershipboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembershipboxActionPerformed
       
        Packageselectedvalue = Membershipbox.getSelectedItem().toString();
        for (Membership memship : GymMangement.memberships)
        {
            if(memship.Membershipname == Packageselectedvalue)
            {
                price = String.valueOf(memship.price);
                Paymentlabel.setText(price);
            }
        }
        
    }//GEN-LAST:event_MembershipboxActionPerformed

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_Close_ButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
       try
       {
        int a=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this member?" , "Select", JOptionPane.YES_NO_OPTION);
        if (a==0)
        { 
           
             IDSearch=Integer.parseInt(IDText.getText());
                try
                {   for (Member mem1 : GymMangement.members)
                    {
                        if(IDSearch==mem1.code)
                        {
                            removedmember=mem1;
                        }
                        ClearFields();
                    }
                    GymMangement.members.remove(removedmember);
                       
                }
                catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
        }
     
                   
       }
        catch(Exception e)
        {
           System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    try{ IDSearch= Integer.parseInt(IDText.getText());}
    catch(Exception e){JOptionPane.showMessageDialog(null,"Please enter ID you want to update");}
            for (Member mem1 : GymMangement.members)
            {
                if(IDSearch==mem1.code)
                {
                    if(UpdateValidation()==true)
                    {
                        mem1.Name = Entername.getText();
                        try{ mem1.Age = Integer.parseInt(Agetext.getText().trim());}
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null,"There was an error try again");
                        }
                        mem1.phonenumber=phonenumbertext.getText().trim();
                        
                        for (Membership memship1  : GymMangement.memberships)
                        {
                            if(memship1.Membershipname.equals(Packageselectedvalue))
                            {
                                mem1.membership = memship1;
                            }
                        }
                    ClearFields();
                    }
                }
            }
      
    }//GEN-LAST:event_updateButtonActionPerformed

    private void AgetextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgetextKeyPressed
   
        lbl_age.setText("");
        
    }//GEN-LAST:event_AgetextKeyPressed

    private void phonenumbertextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumbertextKeyPressed
       
        lbl_phone.setText("");
        
    }//GEN-LAST:event_phonenumbertextKeyPressed

    private void EnternameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnternameKeyPressed
        
        lbl_name.setText("");
        
    }//GEN-LAST:event_EnternameKeyPressed
    private Boolean UpdateValidation()
    {
        if(IDText.getText().trim().isEmpty())
        {
           lbl_ID.setText("You must enter the members ID");
           IDText.requestFocusInWindow();
           return false;
        }
       else if(Entername.getText().trim().isEmpty() )
        {
            lbl_name.setText("You must enter a member name");
            Entername.requestFocusInWindow();
            return false;
        }

       else if(phonenumbertext.getText().trim().isEmpty())
        {
            lbl_phone.setText("You must enter the members phone number");
            phonenumbertext.requestFocusInWindow();
            return false;
        }
       else if( Agetext.getText().trim().isEmpty())
        {
            lbl_age.setText("You must enter the members age");
            Agetext.requestFocusInWindow();
            return false;
        }
        else
        {
          return true;
        }
    }
     private void ClearFields(){
       Entername.setText(null);
       phonenumbertext.setText(null);
       Agetext.setText(null);  
       Membershipbox.setSelectedItem("Daily access");
       IDText.setText(null);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agetext;
    private javax.swing.JButton Close_Button;
    private javax.swing.JTextField Entername;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDText;
    private javax.swing.JComboBox<String> Membershipbox;
    private javax.swing.JLabel Paymentlabel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SearchIDButton;
    private javax.swing.JPanel UpdateDeletePanel;
    private javax.swing.JLabel Update_Delete_Header;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JTextField phonenumbertext;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    }
